#English / Chinese
lang: English
#Allow plugins to perform update detection
update: true
#Allow plugins to perform update detection
store:
  #SQLite / MySQL
  #default SQLite
  mode: SQLite
Mysql:
  address: localhost
  port: 3306
  database: test
  user: root
  password: 123456
HikariCP:
  connectionTimeout: 30000
  minimumIdle: 10
  maximumPoolSize: 50
#Can players refresh a task when they have already accepted a task
can-refresh-accepted: false
  # 随机池每次随机时随机总轮数
  # 每次刷新任务时：
  # 第一轮： 假设有5个任务位置
  #   第一个任务：随机到了普通任务
  #   第二个任务：随机到了普通任务
  #   第三个任务：随机到了稀有任务
  #   第四个任务：每个品质都没随机到
  #   第五个任务：每个品质都没随机到
  # 若第一轮有没被随机到的则进行下一轮
  # 第二轮： 现在第四、五任务没被随机到
  #   第四个任务：随机到史诗品质
  #   第五个任务：仍未被随机到
  #   第二轮还有任务未被随机到，则进行下一轮
  # ....
  # 直到不超过下面设定值的轮数中的某轮第五个任务被随机到商品后结束
  # 或者到了设定值的轮数仍未有任务则该任务为空
refresh-round-max: 20
#该子服是否进行日期检测以及数据刷新工作
#如果你是群组服的并且多个子服在共用同一个数据库时，该选项请保持只有一个子服是打开的，防止数据异常刷新
refresh-enable: true
sounds:
  #The sound effect played when accepting a task
  accept: item_trident_thunder
  #The sound effect played when completing a task
  completed: entity_firework_rocket_launch
  #The sound effect triggered when receiving the final reward
  claim: item_totem_use