name: LegendaryDailyQuests
main: com.gyzer.legendaryrealms.LegendaryDailyQuests
version: 1.1.3
api-version: 1.17
softdepend:
  - Vault
  - PlayerPoints
  - MythicMobs
  - AureliumSkills
  - AuraSkills
  - mcMMO
  - PlaceholderAPI
commands:
  LegendaryDailyQuests:
    aliases:
      - dquests
      - dquest
      - ldq
      - lquest